version: "3.9"

services:
  feeder:
    image: docker-registry.rahti.csc.fi/xinyuan-ma/toyotafeeder:1.0
    environment:
      - "MQTT_URL = mqtt-test.rahtiapp.fi"
      - "MQTT_PORT = 443"
      - "CLIENT_ID = student297"
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
     - "8000:5000"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./certs:/mosquitto/config/certs"

networks:
  studnet297-net: {}


